import Head from "next/head";
import PageTitle from "@/components/common/PageTitle";
import styles from "@/styles/orderDetail.module.css";
import MainLayout from "@/components/common/layouts/MainLayout";
import Image from "next/image";
import CustomizedTables from "@/components/common/detailTable";
import { useEffect, useState } from "react";

export default function Orders() {
  const [orders, setOrders] = useState([]);
  useEffect(() => {
    const savedOrders = localStorage.getItem("orders");
    if (savedOrders) {
      setOrders(JSON.parse(savedOrders));
    }
  }, []);

  console.log(orders);
  return (
    <>
      <Head>
        <title>Orders Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div
          style={{
            width: "100%",
          }}
        >
          <div
            style={{
              marginBottom: "40px",
            }}
          >
            <div
              style={{
                maxWidth: "1468px",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
              }}
            >
              <PageTitle
                title="Order ID # "
                subtitle="Orders / Order Detaills"
                id={orders.userId}
              />
              <div>
                <button className={styles.cancelBtn}>Cancel Order</button>
                <button className={styles.onDelivery}>On Delivery</button>
              </div>
            </div>
          </div>
          <div style={{ display: "flex", alignItems: "start", gap: "40px" }}>
            <div className={styles.leftDiv}>
              <div className={styles.leftTop}>
                <div className={styles.forAvatar}></div>
                <h2>Wahyu Adi Kurniawan</h2>
                <div className={styles.noteOrder}>
                  <h3>Note Order</h3>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua.
                  </p>
                  <div className={styles.noteOrderDelivery}>
                    <Image
                      src="/shipping.png"
                      alt="icon"
                      width={50}
                      height={50}
                    />
                    <p>
                      6 The Avenue, London <br />
                      EC50 4GN
                    </p>
                  </div>
                </div>
              </div>
              <div className={styles.leftBottom}></div>
            </div>
            <div className={styles.rightDiv}>
              <div className={styles.rightTop}>
                <CustomizedTables data={orders.orders} />
              </div>
              <div className={styles.rightBottom}></div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

Orders.getLayout = (pageProps) => (
  <MainLayout>
    <Orders {...pageProps} />
  </MainLayout>
);
