import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import PageTitle from "@/components/common/PageTitle";
import Box from "@mui/material/Box";
import { Grid } from "@mui/material";
import { foodData } from "@/data";
import CustomBtnFood from "@/components/pages/foods/CustomBtnFood";
import { TextField, IconButton, Button, InputAdornment } from "@mui/material";
import SearchIcon from "@mui/icons-material/Search";
import ViewListIcon from "@mui/icons-material/ViewList";
import AppsIcon from "@mui/icons-material/Apps";
import PersonAddIcon from "@mui/icons-material/PersonAdd";

export default function Foods() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div
          style={{
            marginBottom: "25px",
          }}
        >
          <PageTitle
            title="Foods"
            subtitle="Here is your menus summary with graph view"
          />
          {/* <Box
            display="flex"
            alignItems="center"
            gap={1.5}
            p={2}
            bgcolor="#f8f8fb"
          >
            <TextField
              placeholder="Search here"
              variant="outlined"
              size="small"
              sx={{ width: 300, borderRadius: 2, backgroundColor: "#fff" }}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchIcon color="success" />
                  </InputAdornment>
                ),
              }}
            />
            <IconButton sx={{ backgroundColor: "#fff", borderRadius: 2 }}>
              <ViewListIcon />
            </IconButton>
            <IconButton sx={{ backgroundColor: "#fff", borderRadius: 2 }}>
              <AppsIcon />
            </IconButton>
            <Button
              variant="contained"
              startIcon={<PersonAddIcon />}
              sx={{
                textTransform: "none",
                borderRadius: 2,
                backgroundColor: "#00B074",
                "&:hover": {
                  backgroundColor: "#00a066",
                },
              }}
            >
              New Menu
            </Button>
          </Box> */}
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            flexWrap: "wrap",
            gap: "20px",
          }}
        >
          {foodData.map((food) => {
            return (
              <Box
                component="section"
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "end",
                  p: 2,
                  maxWidth: "276px",
                  maxHeight: "433px",
                  minHeight: "433px",
                  position: "relative",
                }}
              >
                <Box
                  sx={{
                    position: "absolute",
                    top: "0px",
                    minWidth: "194px",
                    maxWidth: "194px",
                    minHeight: "194px",
                    maxHeight: "194px",
                    background: "#C4C4C4",
                    boxShadow: "11px 13px 17px 0px #00000026",
                    borderRadius: "50%",
                  }}
                ></Box>
                <Box
                  sx={{
                    backgroundColor: "#FFFFFF",
                    display: "flex",
                    alignItems: "center",
                    flexDirection: "column",
                    maxWidth: "276px",
                    minWidth: "276px",
                    maxHeight: "359px",
                    paddingTop: "182px",
                    minHeight: "359px",
                    borderRadius: "14px",
                  }}
                >
                  <h2
                    style={{
                      maxWidth: "174px",
                      fontFamily: "Barlow",
                      fontWeight: "700",
                      fontSize: "18px",
                      lineHeight: "28px",
                      textAlign: "center",
                    }}
                  >
                    {food.name}
                  </h2>
                  <p
                    style={{
                      fontWeight: "400",
                      fontSize: "14px",
                      lineHeight: "20px",
                      color: "#00B074",
                      marginTop: "7px",
                    }}
                  >
                    {food.cotegoriya} /{" "}
                    <span
                      style={{
                        color: "#5E6C93",
                      }}
                    >
                      {food.type}
                    </span>
                  </p>
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "20px",
                      marginTop: "22px",
                    }}
                  >
                    <CustomBtnFood back="#00B07426" img="/foodIcon.png" />
                    <CustomBtnFood back="#FF5B5B26" img="/foodIcon2.png" />
                    <CustomBtnFood back="#2D9CDB26" img="/foodIcon3.png" />
                    <CustomBtnFood back="#5E6C9326" img="/foodIcon4.png" />
                  </div>
                </Box>
              </Box>
            );
          })}
        </div>
      </div>
    </>
  );
}

Foods.getLayout = (pageProps) => (
  <MainLayout>
    <Foods {...pageProps} />
  </MainLayout>
);
