export const orderListData = [
  {
    userId: 765231,
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    type: "admin",
    orders: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 3,
        review: 253,
      },
      {
        name: "Italiano pizza with garlic",
        count: 2,
        price: 50,
        stars: 1,
        review: 453,
      },
    ],
  },
  {
    userId: 135231,
    date: "26 March 2020, 12:42 AM",
    userName: "Eren Yeager",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    type: "customer",
    orders: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
    ],
  },
  {
    userId: 325231,
    date: "26 March 2020, 12:42 AM",
    userName: "Levi Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    type: "customer",
    status: "Delivered",
    orders: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
    ],
  },
  {
    userId: 555231,
    date: "26 March 2020, 12:42 AM",
    userName: "Armin Melaney",
    location: "Corner Street 5th London",
    amount: 164.52,
    type: "customer",
    status: "New Order",
  },
  {
    userId: 523231,
    date: "26 March 2020, 12:42 AM",
    userName: "Grisha Yeager",
    type: "customer",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    orders: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
    ],
  },
  {
    userId: 558831,
    date: "26 March 2020, 12:42 AM",
    userName: "Historia Reuss",
    location: "Corner Street 5th London",
    amount: 164.52,
    type: "customer",
    orders: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
    ],
    status: "Delivered",
  },
];

export default orderListData;
